{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ng-gateway.fullname" . }}
  labels:
    {{- include "ng-gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ng-gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- range .Values.networkPolicy.policyTypes }}
    - {{ . | quote }}
    {{- end }}
  {{- if and (has "Ingress" .Values.networkPolicy.policyTypes) .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if and (has "Egress" .Values.networkPolicy.policyTypes) .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}

