{{- if and .Values.podMonitor.enabled .Values.gateway.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "ng-gateway.fullname" . }}-gateway
  labels:
    {{- include "ng-gateway.gateway.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ng-gateway.gateway.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      interval: {{ .Values.podMonitor.interval }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
{{- end }}

